---
title: 'Diel patterns of foraging and microhabitat use by sympatric rainbow trout and bull trout: implications for adaptive differentiation and instream flow assessment'
csl: canadian-journal-of-fisheries-and-aquatic-sciences.csl
header-includes:
- \usepackage{lineno}
- \linenumbers
- \usepackage{setspace}\doublespacing
- \setlength{\parskip}{1em}
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    latex_engine: xelatex
  word_document: default
bibliography: References.bib
---

\begin{center}
Sean M. Naman$^{1,2*}$, Jordan S. Rosenfeld$^3$, Alecia S. Lannan$^{1, 4}$
\end{center}

\vspace{2cm}


1. Department of Geography, University of British Columbia, Vancouver, BC, Canada
2. Current affiliation: Earth to Ocean Group, Simon Fraser University, Burnaby, BC, Canada
*Corresponding author: sean_naman@sfu.ca, 604-619-4274 
3. Conservation Science Section, BC Ministry of Environment, Vancouver, BC Canada
4. Current affiliation: Ecofish Research Ltd. Vancouver, BC Canada
\vspace{4cm}

\raggedright\large
Key words: Foraging, predation risk, habitat suitability
\newpage

# Abstract
Salmonids make flexible and adaptive trade-offs between foraging efficiency and predation risk that result in variable patterns of diel activity and habitat use. However, it remains unclear: (1) how patterns differ among salmonid species; and (2) how this affects the interpretation of habitat suitability models that inform instream flow management. We combined snorkel observations with experimental additions of cover to investigate how predation risk, cover, and bioenergetics affect diel activity and habitat use patterns by sympatric rainbow trout and bull trout in the Skagit River, BC, Canada. Both species foraged primarily at dusk, supporting the well-described trade-off between foraging efficiency and predation risk. However, only rainbow trout responded to cover additions, suggesting that risk tolerance and the nature of foraging-predation risk trade-offs differ between species. Diel shifts in activity and habitat use also substantially altered predictions of habitat suitability models, with potentially large consequences for flow management. 


# Introduction
Stream salmonids are well known for flexible diel activity patterns, with feeding chronology ranging from being diurnal (day active), nocturnal (night active), or crepuscular [active at dusk and dawn; @Alanara1997; @Bradford2001]. Microhabitat selection is closely related to activity and also exhibits strong diel variability, since alternative activities (e.g., feeding, resting, and avoiding predators) require different habitat features. For example, intermediate water velocities optimize energy intake when feeding on drifting invertebrates, while low velocity microhabitats minimize energy expenditure when resting [@FauschWhite1981]. Similarly, structural cover may be critical for fish to avoid visual predators during the day [@Harvey2016; @Wilzbach1985], but less important during crepuscular periods or at night when predation risk is greatly reduced.

Optimizing energy acquisition vs. avoiding predation are the competing endpoints of a continuum that determines realized habitat selection. Diel patterns of activity and habitat use therefore reflect a complex state-dependent trade-off between growth and survival, which tracks fluctuations in foraging efficiency, predation risk, and prey abundance [@Railsback2005; @Metcalfe1999]. Generally, foraging in daylight is more efficient but incurs higher predation risk [@Fraser1997; @Wilzbach1986a]. Food abundance also has a strong temporal signature, often increasing as light levels decline due to elevated invertebrate drift [@Bishop1969a; @Naman2016]. Collectively, these fluctuating conditions, along with attributes of individual fish (e.g., body size, energetic status), interactively determine diel patterns of activity and habitat use. This is well described by theory [@Railsback2020], yet the drivers of realized patterns in natural systems, e.g., predation risk vs. food abundance, are challenging to disentangle. Further, different salmonid species often exhibit contrasting activity and habitat use patterns [@Hearn1987], which may relate to poorly understood differences in behaviour, morphology, or physiology that determine the strength and shape of growth-survival trade-offs. 

Better understanding the underlying drivers of diel activity and habitat use patterns across species informs both our understanding of adaptive differentiation and management needs. First, divergent diel activity patterns may be a critical yet underappreciated dimension of resource partitioning that facilitates coexistence of sympatric salmonid species [@Young2004; @Kronfeld]. Second, diel variation in microhabitat use can influence the development and application of habitat suitability models that are integral to instream flow management and habitat restoration (Railsback et al. 2020b). These models are commonly derived from snapshot observations of diurnal habitat use and rarely consider temporally varying habitat requirements [but see @Harris1992; @Roussel1999; @Al-Chokhachy2007a]. Recent simulation modelling by @Railsback2020b indicates that ignoring diel activity variation can introduce significant bias into habitat suitability model predictions, and ultimately undermine management. Yet, this bias is not well documented empirically.

Here we consider the ecological and applied implications of diel variation in activity and habitat use by sympatric juvenile rainbow trout *Onchorhynchus mykiss* and bull trout *Salvelinus confluentes* in the Skagit River, Southwest British Columbia, Canada. These species often exhibit contrasting patterns of diel activity, with bull trout showing a more consistent nocturnal bias relative to rainbow trout, which are more variable [@Jakober2000; @Angradi1990; @Elliott1973]. First, we compared diel patterns of microhabitat use and behaviour between the two species to determine how they overlap in space and time. Second, we combined measurements of prey abundance with experimental additions of cover from predators to differentiate the roles of hydraulic constraints (i.e. velocity and depth) vs. predation risk in determining habitat use. We reasoned that if fish foraged near added cover during the day, it would suggest predation risk was a key driver of habitat use and activity patterns. As a corollary, contrasting responses to cover between species would then indicate differences in growth-survival trade-offs that underlie activity patterns. Third, we compared simple habitat suitability models developed from observations during the day, dusk, and night to assess how diel variability in habitat use modifies habitat suitability predictions for both species.

Based on previous work on the ecology of these species, we made several *a priori* predictions. First, we expected that bull trout would be more nocturnal than rainbow trout, i.e., that more bull trout would be observed foraging at night [@Baxter1997a]. Second, we predicted that if predation risk were a strong influence on diurnal habitat use and activity, experimental additions of cover that provide shelter from predators would be colonized by daytime foraging fish. We anticipated that this effect would be more pronounced for rainbow trout given their greater tendency for diurnal foraging. Third, we predicted that habitat suitability model predictions would be sensitive to time of day, with daylight habitat use biased towards lower velocity resting microhabitats or structural cover from predators. 





# Methods

*Study Location*

We conducted our study in the upper Skagit River watershed in Southwest, British Columbia, Canada near the confluence of the Skagit and Sumallo Rivers. The Skagit flows south from British Columbia into Ross Lake reservoir in the United States, eventually draining into Puget Sound. The 99,768 ha watershed is comprised primarily of second growth coniferous forest, with 70% of its area protected as a Provincial Park. We selected five 100 m reaches based on representative geomorphic characteristics of the upper watershed and accessibility, which was limited due to wildfires. Two reaches on the Sumallo River had lower gradient pool-riffle morphology and predominantly well sorted gravel and cobble substrate; the three mainstem Skagit reaches were higher gradient, with more heterogeneous substrate composition that included larger boulders. Mean daily temperatures ranged from 9-11&deg;C across all sites throughout the duration of the study (August and September 2018; US National Park Service *unpublished data*). 

Rainbow trout, bull trout, and dolly varden (*S. malma*) are present in the watershed; however, dolly varden occur mainly in smaller tributaries and were not directly observed in this study. There is limited information about rainbow trout and bull trout populations in the upper Skagit, but there are likely resident and adfluvial life histories present in both species (Skagit Environmental Endowment Commission personal communication).


*Field Methods* 

Our approach combined measurements of physical habitat attributes and invertebrate prey abundance, snorkel observations of habitat use and activity by juvenile rainbow trout and bull trout, and a manipulative experiment of cover designed to test the influence of predation risk on diel habitat use and behaviour. We describe each of these components in detail below.

*Habitat and Behaviour Observations* - To determine habitat availability, we conducted systematic point transects of depth, velocity, substrate, and cover in each reach (Appendix 1). Reaches were first broken into distinct geomorphic channel unit types following Hawkins (1988), then transects with 0.2 m point spacing were placed at the midpoint of each channel unit perpendicular to flow. At each point, we measured total water depth and velocity at 60% below the surface using an acoustic doppler velocimeter (ADV - Flow Tracker 2, Sontek Corporation). We visually classified substrate size into one of 5 size classes following a Wentworth classification scale (Wentworth 1922). Cover was estimated as present if structurally complex elements (e.g., wood) or overhanging vegetation was observed within the transect cell (0.2 m to the left and right of velocity and depth measurement). Because many fish were observed hiding in interstitial spaces underneath larger substrate in snorkel surveys, we considered substrate over 25 cm (substrate class 4 and above) as cover. Estimating cover is inherently subjective and our classification likely missed nuanced differences among different structural elements; however, it captured broad differences between habitats where fish would be conspicuous and habitats that would likely provide refuge from predators.

To quantify the role of diel variation in prey abundance, we measured invertebrate drift during the day and at dusk in each reach on the same day as snorkel observations of fish. Three 250 $\mu$M drift nets (306 cm$^2$) were set at the most upstream riffle habitat in each reach, and left for two replicate 30 minute sets. We measured velocity and depth at the opening of each net at the beginning and end of each set, then computed the total volume filtered. Day sampling occurred between 10h00 and 14h00 and dusk sampling occurred within the hour around civil twilight. Drift samples (*n* = 3 per reach) were stored in 95% ethanol, then sorted in the laboratory, identified to family or order, and measured to the nearest 0.1 mm using an ocular micrometer. We used published regression equations to relate body lengths to biomass [@Benke1999].

We characterized rainbow trout and bull trout activity and microhabitat use patterns by snorkeling. Fish were located by an observer, moving upstream from the lower end of each reach. A dive flashlight was necessary to locate fish during dusk and night surveys, and to search under substrate and wood for hiding fish during the day. Once located, individual fish were observed for 1-3 minutes and their activity was recorded as either “resting”, if they were motionless on the streambed, or “foraging”, if they held a focal position in the water column to scan for invertebrate drift. In rare cases, activity was ambiguous and these observations were not included in analysis. We estimated body lengths of fish using marks placed on the observers diving gloves as a reference. The timing of fish observations corresponded to the day and dusk windows of drift sampling; night observations started at least two hours after civil twilight.

In total, we observed the behaviour and microhabitat use of 192 bull trout and 265 rainbow trout across the five reaches. Bull trout were larger than rainbow trout on average (bull trout: 83 $\pm$ 25; rainbow: 62 $\pm$ 25 mm), and the average size of both species increased from day (bull trout: 68 $\pm$ 14 mm; rainbow: 50 $\pm$ 12 mm), to dusk (bull trout: 88 $\pm$ 25 mm; rainbow: 62 $\pm$ 23 mm) to night (bull trout: 91 $\pm$ 28 mm; rainbow: 79 $\pm$ 30 mm) observations. After behaviour was assigned and length was estimated, the exact location of the fish was marked with a large washer for subsequent measurements of microhabitat features; these included water depth, velocity at the focal point of the fish and at 60% of the total water depth, focal point depth (as a proportion of total water depth), substrate size, and whether structural cover was present. 


*Cover manipulation experiment* - To determine if predation risk was driving diel activity and habitat use patterns, and if foraging-predation risk trade-offs varied between species, we measured the responses of fish to experimental additions of structural cover. We constructed three sided boxes (40 cm L x 15 cm W x 20 cm H) that were open facing the stream bed and at the upstream and downstream ends, with natural branches attached on the underside to simulate structural cover from wood (Figure 1). Boxes were oriented with the closed sides parallel to flow to minimize impacts on local hydraulics (Appendix 2) and anchored to the stream bottom with rebar stakes. We left boxes undisturbed for four days, then returned to each box and observed whether fish were present and actively foraging. Species and size of each observed fish was estimated as described above in the snorkel survey methods. 

Our placement of boxes was designed to encompass a range of hydraulic conditions, including: (1) areas where we observed fish foraging at dusk but not during the day; (2) apparently unsuitable drift-foraging areas with zero velocity; and (3) unsuitable foraging areas with high velocity ( > 60 cm s $^{-1}$). We hypothesized that if predation risk was a key factor restricting diurnal foraging, cover added to more suitable foraging locations should be colonized by daytime foraging fish. No fish were observed foraging during the day at any cover box sites prior to their placement. 

Because the suitability of foraging habitat is influenced by food abundance in addition to velocity and depth, we combined measurements of velocity with stream-averaged daytime invertebrate drift concentrations to estimate the potential net rate of energy intake (NREI Joules s$^{-1}$) in each location where cover was added (Appendix 2). NREI is defined as the total rate of energy gained from drift foraging less the costs of swimming, maneuvering, and basic metabolic demands [@Hughes1990b; @Piccolo2014]. We implemented the drift-foraging bioenergetics model using the freeware program BioenergeticHSC [described in @Naman2020b].  

*Statistical analysis*

*Diel activity and habitat use patterns*- All statistical analyses were conducted in R version 4.0.2 (R Core Development Team). To determine whether activity (foraging vs. resting) differed for each species through time and between species within a given time period, we used Z-tests of equal proportions or Fisher exact probability test (when *n* < 5 observations). We then used a combination of univariate and multivariate approaches to examine differences in microhabitat use between species (rainbow vs. bull trout) and activities (foraging vs. resting) throughout the diel cycle. To examine how species differed in depth and velocity microhabitat use, we compared focal point velocity, water depth, and focal depth across all combinations of species and activity in each time period (day, dusk night) using Kruskal-Wallis rank sum tests because parametric assumptions could not be met. Where Kruskal-Wallis tests were significant (*P* < 0.05), we used pairwise Wilcoxon rank-sum tests to identify what activity by species drove the differences. A Holm correction factor was applied to account for inflated type 1 error with multiple comparisons. 

To evaluate microhabitat overlap in multivariate space, we conducted a Canonical Analysis of Principal Coordinates [CAP; @Anderson2003]. CAP is a constrained ordination procedure designed to uncover patterns in multivariate data where there are *a priori* hypotheses about differences among groups. For each time period, we determined the extent that microhabitat features used by fish diverged according to species and activity. Microhabitat variables included focal velocity, water depth, focal depth (as a proportion of water depth), average water column velocity, cover presence, and relative substrate size. We performed the CAP analysis on a Gower similarity matrix of scaled habitat variables using the *capscale* function from the vegan package in R [@Oskanen2013]. We then tested the significance of constrained axes using permutation tests (*anova.cca* function in vegan). 

Body size can be another important determinant of diel habitat use and activity. However, we did not incorporate body length into our formal statistical analysis for several reasons: first, we did not have information on length-age relationships in the Skagit system and exploratory size-frequency plots did not reveal clear age classes; and second, creating length class bins would have reduced statistical power due to low numbers of observations. Therefore, we consider bull trout and rainbow trout as a single assemblage of juvenile fish, but recognize that body size differences may contribute to observed variation.

*Cover manipulation* - Predation risk and hydraulic habitat quality may act as hierarchical habitat filters determining microhabitat occupancy by fish. We tested whether the probability of diurnal cover box occupancy by foraging fish increased in more energetically profitable areas (i.e., higher NREI). We used a generalized linear model (GLM) with a binomial error distribution and a logit link function to estimate the probability of occupancy (scaled 0 to 1) as a function of NREI,  then applied a likelihood ratio test to compare the effect of NREI to a reduced model with only an intercept term. 

Colonization of cover boxes could occur by two distinct pathways: (1) nocturnal and crepuscular foragers becoming day-active; or (2) diurnal foragers redistributing to forage under the added cover. Because size distributions varied with time of day, they can potentially inform these alternate mechanisms. Similar size distributions between fish using added cover and fish observed at dusk would support altered diel activity patterns; alternatively, similar size distributions between fish using added cover and fish observed during the day would support re-distribution. We used two-sample Kolmogorov-Smirnov tests to compare size distributions of fish we observed foraging under added cover to fish foraging at dusk vs. during the day


*Invertebrate drift abundance and size distribution* - We compared the invertebrate drift abundance between day and dusk using one-way analysis of variance. We also examined drift size distributions to test the prediction that drift at dusk would have more large invertebrates, which has a strong bearing on the energetic profitability of foraging [@Dodrill2016b]. We fit gamma distributions to pooled drift data from each time period using the R package *fitrdistplus*. Rate ($\beta$) and shape ($\alpha$) parameters from the gamma distributions ($g(x|\beta,\alpha)$) were then bootstrapped and used to make inferences into differences in drift size distributions. Specifically, we compared bootstrapped 95% confidence intervals of the mean size ($\alpha/\beta$) and the skewness ($2/\sqrt(\alpha)$), where a greater negative skewness value indicates a larger proportion of larger individuals. 

*Habitat suitability modelling* - To investigate how diel changes in microhabitat use patterns influence habitat suitability models, we developed diurnal, crepuscular, and nocturnal univariate habitat suitability curves (HSCs) for water depth, average water column velocity, substrate, and cover presence. HSCs are widely used indices of habitat quality based on ratios of habitat use to habitat availability, standardized between 0 and 1 [@Nestler2019]. We pooled habitat use frequencies across all individuals for a given species and time of day. Similarly, we pooled habitat availability from transect data across all reaches, weighted by the relative area each transect represented. This approach assumes that our habitat sampling is representative of the conditions available to fish in the Skagit system. 


For each species and time period, we used binomial GLMs with a logit link function to generate HSCs by relating the availability of a given habitat feature to the relative probability of habitat use. This method is analogous to resource selection functions based on logistic regression [@Ayllon2012a]. We tested linear and second order polynomial terms for each habitat variable and retained the most parsimonious model based on Akiake's Information Criterion (AIC) adjusted for small sample sizes [@Burnham2002]. Model predictions were then rescaled to a maximum of 1. Depth and velocity data were binned into intervals of 5 cm and 5 cm s$^{-1}$ for this analysis. This univariate HSC method effectively ignores model prediction uncertainty as well as potential interactions among habitat features. However, our goal was to replicate univariate HSCs that are typically developed and used by practitioners [@Nestler2019], and to consider the implications of qualitative differences in the shape of HSCs among time periods and between species. Thus, we did not pursue a more rigorous statistical approach. 

Due to limited sample size, we were not able to directly calculate separate HSCs for foraging vs. resting fish. However, because the of strong temporal trend in activity patterns (see *Results*), HSCs compared across time periods largely reflect differences between these contrasting behaviours. While we report habitat suitability results for substrate, and cover, we focus our inference and discussion on HSCs for velocity and depth.


#Results

*Patterns of activity and microhabitat use* - Both rainbow trout and bull trout activity exhibited striking diel patterns, with a significantly higher proportion of fish foraging at dusk relative to day or night (Figure 2; rainbow:, $\chi^2$ = 95.682, *P* < 0.001; bull trout: $\chi^2$ = 69.448, *P* < 0.001). Species differences were also evident, but were not as pronounced as differences among time periods. During the day 61% of rainbow trout were foraging relative to only 25% of bull trout ($\chi^2$ = 15.63, *P* < 0.001), and at dusk 97% of rainbow trout were foraging relative to 81% of bull trout ($\chi^2$ = 9.89, *P* = 0.002). Both species switched to primarily resting behaviour at night, and contrary to expectations, there were no differences in the proportion of foraging vs. resting fish between species (rainbow = 24% foraging; bull trout = 16% foraging, $\chi^2$ = 1.13, *P* = 0.29).  

Microhabitat use also exhibited diel variation; in particular, there was a strong crepuscular shift towards decreased use of cover by both species (rainbow: $\chi^2$ = 91.39, *P* < 0.001; bull trout: $\chi^2$ = 64.57, *P* < 0.001). 86% of rainbow trout and 100% of bull trout were associated with cover in daylight, then at dusk cover use decreased to 19% of rainbow trout and 32% of bull trout. Nocturnal cover use remained lower than in daylight but was slightly elevated relative to dusk (35% of rainbow trout and 42% of bull trout) when species were mostly drift-feeding. Species contrasts in cover were only statistically different during daylight, when 14% fewer rainbow trout were associated with cover than bull trout (Fisher exact test: *P* = 0.002; dusk: $\chi^2$= 2.89, *P* = 0.09; night: $\chi^2$ = 0.45, *P* = 0.50).  

Daytime velocity use differed with activity ($\chi^2$ = 75.862, *P* < 0.001), with foraging rainbow and bull trout occupying faster velocities than their resting conspecifics (Figure 3; Wilcox rank sum test: bull trout foraging vs. resting *P* < 0.001; rainbow trout foraging vs. resting *P* < 0.001); however, focal velocities did not differ between species for a given activity (Wilcox rank sum test; foraging *P* = 0.44, resting *P* = 0.43). At dusk, foraging individuals continued to occupy faster velocities than resting individuals ($\chi^2$ = 23.292, *P* < 0.001), and small differences in focal foraging velocities emerged between species, with foraging rainbow trout occupying faster velocities than bull trout (*P* = 0.043). This difference did not persist at night; although foraging fish still occupied faster velocities than resting individuals ($\chi^2$ = 28.106, *P* < 0.001; rainbow foraging vs. resting *P* = 0.002; bull trout foraging vs. resting *P* = 0.001).

Depth use differed more between species than activities. During the day, differences in depth use ($\chi^2$ = 20.565, *P* < 0.001) were driven by foraging bull trout foraging in deeper habitats than other groups (*P* < 0.001 across all pairwise comparisons). At dusk, bull trout continued to occupy deeper habitats than rainbow trout ($\chi^2$ = 25.387, *P* < 0.001), but there were no differences in depth use between resting and foraging fish (*P* = 0.98). At night, differences were evident across species and activities ($\chi^2$ = 22.926, *P* < 0.001), with bull trout generally occupying deeper habitat (*P* = 0.001). 


Multivariate CAP analysis further supported divergent microhabitat use between species and activities (Figure 4); however, the overall variance explained by the constrained axes was low (Day: 26%; Dusk: 8%; Night: 15%). During the day, the primary axis of separation (explaining 88% of the constrained variance) was driven by increasing focal velocity and decreasing average velocity, focal depth, and substrate (species: SS = 0.19, *F* = 6.16, *P* < 0.001; activity: SS = 1.09, *F* = 35.03, *P* < 0.001), indicating a contrast in microhabitat selection between foraging and resting fish. The second axis explained 11% of the constrained variance and was driven by increasing water depth and cover presence, which tended to separate bull trout from rainbow trout. At dusk, the overwhelming majority of constrained variance (93%) was driven by increasing total depth, focal depth, and cover, and decreasing substrate size and focal and average velocity (species: SS = 0.55, *F* = 9.84, *P* < 0.001; activity: SS = 0.12, *F* = 2.18, *P* = 0.048), which again separated bull trout (deeper, lower velocity) from rainbow trout (shallower, higher velocity).  At night, the primary axis explained 81% of the constrained variation and was driven by increasing velocity (focal and average) and decreasing focal depth that differentiated foraging and resting fish. The second axis explained 19% of the constrained variation and was driven by increasing substrate size and decreasing total depth (species: SS = 0.19, *F* = 4.26, *P* = 0.004; activity: SS = 0.83, *F* = 18.69, *P* < 0.001), again reflecting differences in resting habitat selection between bull trout (deeper) and rainbow trout (shallower). 

Irrespective of time of day, resting individuals of both species were associated with lower focal velocities than foraging individuals. However, the contribution of other habitat attributes was dynamic. For instance, foraging microhabitats were associated with deeper water depths and smaller substrate size during the day, then shifted to shallow depths and larger substrate at dusk (Figure 4). Species contrasts were more pronounced when foraging relative to resting, with foraging rainbow trout occupying faster, shallower habitats than foraging bull trout, but differences were no longer apparent when fish were at rest. 


*Cover addition experiment: predation risk and food abundance* - In line with our predictions, cover boxes that were placed in more suitable foraging velocities, as determined by NREI, had a higher probability of being occupied by rainbow trout (Likelihood Ratio Test $\chi^2$ = 11.397, Deviance = 33.27, *P* = 0.001; Figure 5). Kolmogorov-Smirnov tests indicated that fish foraging in the added cover were smaller than those foraging fish at dusk (Figure S3; *D* = 0.398, *P* = 0.02) and similar to those foraging during the day (*D* = 0.19, *P* = 0.70). No bull trout of any size colonized the cover boxes.


Also in line with predictions, invertebrate drift concentration increased at dusk relative to day (Figure S4). The number of drifting invertebrates increased at dusk from 5.4 m$^{-3}$ to 22.5$^{-3}$ (ANOVA *F* = 20.82, *P* = 0.001; 95% CIs: day = 0.28-10.65; dusk = 15.99-29.10) and the biomass concentration of drifting invertebrates increased from 0.8 mg m$^{-3}$ to 4.6 m$^{-3}$ (*F* = 6.82, *P* = 0.02; 95% CIs: day = 0-2.79; dusk = 2.12-7.02).  In addition, invertebrates drifting at dusk were larger on average (mean day: 1.7 mm, 95% CIs = 1.6-1.8 mm; mean dusk: 2.0 mm, 95% CIs = 1.9-2.1 mm) and were less skewed towards smaller individuals (skewness day: 1.12, 95% CIs = 1.09-1.13; dusk: 1.09, 95% CIs = 1.08-1.1).


*Effects of diel behaviour on habitat suitability criteria* - Univariate HSCs exhibited marked differences across time periods and species (Figure 6). For rainbow trout, optimal velocities shifted from 0 m s$^{-1}$ during the day, when fish were concealed under low velocity cover, to 0.45 m s$^{-1}$ at dusk when fish were primarily drift-foraging in the open. At night, optimal velocities declined to 0.25 m s$^{-1}$, reflecting a mix of activities. By contrast, optimal velocities for bull trout were similar between day and night (0.25 and 0.3 m s$^{-1}$) but shifted to 0 m s$^{-1}$ at dusk. However, bull trout HSCs should be tempered by low sample sizes. Depth HSCs for both species shifted from a linear increase in suitability with depth during the day, to distinct peaks at dusk and at night (Figure 6). Optimal dusk and night depths were similar for rainbow trout but optimal depths for bull trout declined from dusk (1.1 m) to night (0.65 m). HSCs for substrate and cover reflected the observed diel shifts in behaviour and exhibited contrasts between species. For rainbow trout, microhabitats with cover had  higher suitability values during the day, but lower values at night (Figure 6). Alternatively, there was less diel variability in cover suitability for bull trout, except for the strong increase in suitability for 'No cover' microhabitats from daylight to dusk and night. There was also diel variation in substrate suitability. Bull trout shifted from larger substrate during the day to smaller substrate at dusk and night. Directional patterns were less clear for rainbow trout (Figure 6).




#Discussion

*Diel activity and habitat use patterns*


Rainbow trout and bull trout in the Skagit River exhibited striking and broadly consistent diel activity patterns, where foraging was predominately crepuscular. While not universal, this is a common pattern observed in stream salmonids [e.g., @Alanara1997; @Sato2014] that is supported by theory relating diel activity to foraging-predation risk trade-offs [@Railsback2020]. These investigations suggest that elevated prey abundance, moderate foraging efficiency, and reduced predation risk during crepuscular periods offers salmonids a positive balance of risk and reward. Our results support this interpretation. At dusk, drifting invertebrates were larger and more abundant, and the majority of fish were not associated with structural cover, suggesting predation risk was no longer a strong constraint on habitat selection. Temporal shifts in activity patterns were paralleled by shifts in microhabitat use, reflecting the dynamic suite of habitat conditions required for feeding, resting, and predator avoidance. These include structural cover in slower stream margins during the day, faster velocities that are energetically profitable for drift-foraging at dusk, and slower resting velocities at night.


Despite broadly similar activity and habitat use patterns, nuanced differences were still evident between the two species. First, bull trout foraged less frequently during the day than rainbow trout, which aligns with previous work on these taxa [@Angradi1990; @Baxter1997a]. However, there was no evidence that bull trout foraged more frequently than rainbow trout at dusk or at night, i.e., there was a higher proportion of rainbow trout foraging in all time periods. This could suggest that juvenile bull trout allocate less effort to foraging than rainbow trout due divergence in physiology or life history traits (discussed further below). Alternatively, it could reflect bull trout using other foraging modes, such as benthic or interstitial search foraging [@Nakano1992] that our snapshot observations did not capture. 


Second, multivariate analyses illuminated subtle differences in microhabitat use, with rainbow trout foraging in faster, shallower areas than bull trout during both day and at dusk. Rainbow trout using higher velocities than other species is generally consistent with previous studies [@Bisson1988], as is the association of bull trout with deeper slower microhabitats [@Al-Chokhachy2007a; @Polacek2003a]. By contrast, microhabitat partitioning was less pronounced among resting individuals, which generally presented as a mixed assemblage associated with lower velocities.

Collectively, these results provide only limited support for the role of temporal resource partitioning as a strong mechanism of rainbow trout and bull trout coexistence in the upper Skagit system. Instead, our findings suggests that these species are dealing with broadly similar constraints to their activity and habitat use patterns, and that differentiation is nuanced and potentially cryptic (see discussion of cover experiment below). Further, the extent of habitat overlap we observed suggests these species may compete for foraging, resting, or refuging habitat [@Nakano1999a; @FauschWhite1981]. However, since our study was observational we cannot make direct inferences concerning competition, and additional work is necessary to investigate this possibility. 


*Experimental cover additions and potential mechanisms of adaptive differentiation*

Experimental cover additions illuminated the influence of predation risk on diel habitat use patterns, as well as key differences between species. Colonization of cover boxes by rainbow trout was consistent with the hypothesis that predation risk is a key driver of diel activity and habitat shifts, limiting daytime foraging away from cover. The ability of NREI to predict the colonization probability of a given cover box further reinforces this inference. In essence, this finding highlights the role of predation risk as a constraint on diurnal habitat use and the presence of structural cover as a key dimension of habitat quality [@Kawai2014; @Boss2002; but see @Larranaga2015]. 


Colonization of cover boxes by smaller fish indicates redistribution of smaller diurnal foragers to more profitable locations, rather than shifts in diel activity patterns (i.e., larger fish shifting from crepuscular to diurnal foraging). The lack of response by larger fish to cover additions could relate to additional diurnal foraging not being sufficiently beneficial for larger individuals. For instance, if fish can meet their metabolic demands during crepuscular periods when food is more abundant, foraging under the added cover in daylight would have limited benefit. Another possibility is that the added cover may not have sufficiently reduced the threat of predation for larger fish that are often more risk averse [@Naman2019b]. We are unable to disentangle these mechanisms; however, on the whole these results align with theory and observations of size-dependent diel foraging patterns [@Sato2014; @Railsback2020].

In contrast to rainbow trout, no bull trout of any size colonized any of the cover boxes. This striking result cannot be explained by differences in body size between species, given that many bull trout observed during the day were within the size range of rainbow trout that colonized the added cover. Interspecific competition is also an unlikely explanation, given that ~30% of cover boxes remained unoccupied despite being in energetically profitable locations (NREI > 0). Instead, we posit that these contrasting responses relate to divergent traits between these species that modify foraging-predation risk trade-offs and how individuals respond to them.

Adaptive divergence in juvenile salmonids is best understood in terms of the integrated phenotype, where niche differentiation results in a suite of integrated physiological, behavioural, and morphological traits that determine species performance in different habitats [@Monnet2020; @Rosenfeld2020]. For example, Rosenfeld et al. (2020) showed that sympatric juvenile rainbow trout and coho salmon are adaptively differentiated along and axis of high food consumption and low growth efficiency (trout)  vs. lower food consumption and high growth efficiency (coho salmon). Similarly, there may be a number of adaptive trait combinations that underlie adaptive differentiation between rainbow trout and bull trout; here we discuss two particularly intriguing possibilities. First, species in the genus *Salvelinus* (including bull trout) appear to feed more efficiently at low light levels than species in the genus *Oncorhynchus* (including rainbow trout) [@Elliott2011]. Consequently, bull trout may receive a lower marginal benefit from the diurnal foraging opportunities provided by the added cover. More detailed observations of foraging efficiency or stomach fullness would shed further light on this possibility. Second, fundamental differences in risk aversion may stem from contrasting life history strategies between the species. While there is significant variability, these species (and *Oncorynchus* and *Salvelinus* more generally) diverge across a growth-longevity axis, with rainbow trout tending to exhibit earlier age at maturity and faster early growth relative to bull trout [@Quinn2018; @McCubbins2016; @Erhardt2016]. As a result, juvenile rainbow may exhibit integrated traits associated with a 'faster' pace of life syndrome [@Reale2010], which includes higher prey consumption and bolder risk-taking behaviour driven by higher metabolic demands [@Monnet2020; @Tyler2008; @Mesa2013]. By contrast, juvenile bull trout may exhibit a more risk averse strategy and grow slowly before transitioning into piscivory as sub-adults [@Rieman1993a]. Additional life history information on these species would be valuable in the Skagit, which likely includes both stream-resident and adfluvial population components. 

While our observation of crepuscular foraging by bull trout is consistent with their known behaviour, not all rainbow trout populations are predominantly crepuscular.  For example, juvenile anadromous rainbow trout (steelhead) and coho salmon were observed to actively forage throughout the day away from cover in nearby coastal watersheds with similar food abundance as the Skagit [@Naman2019]. This suggests qualitative differences in predation risk between systems.  One possibility is elevated predation risk associated with the presence of larger piscivorous bull trout, which prey on younger age classes [@Pinto2013] and may be active in daylight [@Eckman2016]. Crepuscular foraging in the presence of adult bull trout may be a flexible adaptation in sympatric juvenile rainbow trout but a fixed one in juvenile bull trout that always experience high risk from older age classes.  Alternatively, predation risk in the presence of larger resident trout may restrict juvenile daytime foraging irrespective of species [@Walters1993a], while remaining low in anadromous streams that often lack larger resident piscivores. A more systematic assessment of rainbow trout diel foraging behaviour in anadromous vs. resident streams is required to properly evaluate this hypothesis.

We acknowledge that our insights into these potential mechanisms of adaptive differentiation are speculative given the limited information available in the upper Skagit system and the wide variation in behavioural, physiological, and life history traits *within* salmonid species [e.g., @McMillan2012]. Nonetheless, our results highlight the importance of further understanding the cryptic axes of differentiation among sympatric stream salmonids; in particular, divergent responses to variability in habitat conditions [@Bradford2001], predation risk [@Harvey2013, this study], or resource abundance [@Bailey2020] that collectively define the integrated phenotype. 



*Implications for habitat suitability modelling*

The observation that salmonid microhabitat use varies throughout the day is not new, yet many habitat suitability models for salmonids are based only on daytime observations [@Nestler2019; @Railsback2020b]. Our qualitative comparisons of HSCs generated in distinct diel phases highlight potential issues that may arise with species that show temporal variation in habitat use. Most notably, the peaks of velocity HSCs for rainbow trout shifted from near 0 m s$^{-1}$ during the day to ~0.5 m s $^{-1}$ at dusk, when the majority of individuals were drift-feeding. This suggests that suitability criteria generated from daylight observations will poorly represent the habitat conditions required for energy acquisition for fish populations that refuge during the day due to high predation risk. Consequently, these populations may be more sensitive to altered velocity distributions (e.g., through flow reduction) than daytime habitat suitability predictions would suggest (Railsback et al. 2020b). For example, a diel HSC with a peak at 0 m s$^{-1}$ would predict that very low velocities (and therefore flows) would be optimal for fish production. However, flows that maximize zero velocity microhabitats that trout use during the day in the Skagit would severely reduce the area of high energy flux microhabitats necessary for trout to maximize energy intake during crepuscular foraging.

A further challenge is that diel habitat use patterns are variable across diverse conditions. For example, the extent of diurnal foraging is often strongly related to temperature, which drives metabolic demands [@Fraser1993]. Similarly, the magnitude of risk from different terrestrial and aquatic predators varies seasonally and across systems [@Harvey2013]. These conditions, along with inter-individual variation, will ultimately determine the extent of diel habitat shifts and the consequences of developing and applying fish-habitat relationships across time periods. Borrowing literature-derived HSCs may therefore introduce significant error; for example, borrowing HSCs with unknown predation risk may be inappropriate if they are based on daytime refuging behavior that poorly represents foraging velocity selection.

How can habitat suitability assessments account for this complexity? Unlike individual based modelling approaches, habitat suitability models based on frequency-of-use observations cannot deal with the mechanistic drivers of habitat selection explicitly. However, a basic approach could be to observe fish across the full diel cycle, then generate separate HSCs from different times. These HSCs would then define a range of habitat suitability predictions to inform management or be used for sensitivity analysis (Railsback et al. 2020b). For example, juvenile salmonid instream flow requirements in the Skagit could be conservatively based on crepuscular velocity requirements that maximize feeding opportunities, since foraging is essential for growth and the most flow-demanding behaviour. While this approach would require additional field effort, it would likely reduce the potential bias associated with predation risk and diel variation in habitat use. 


#Acknowledgements
We are grateful to the Skagit Environmental Endowment Commission and the Natural Sciences and Engineering Research Council for supporting this work. Danielle Courcelles, Ashley Rawhauser, Rob Wilson, Kevin Wilson provided helpful advice on study design and logistics. Paige Lewis and Thomas Smith helped with field data collection and Alyssa Nonis assisted with invertebrate sorting. Scott Denkers and Chris Tunnoch also provided invaluable advice and support in initiating this project. Two anonymous reviewers provided helpful comments that improved the manuscript.

#Contributions
SN and JR conceived and designed the study; SN, AL, and JR conducted the fieldwork; SN analyzed the data and wrote the initial draft of the manuscript; and all authors contributed to revisions. 

#Data Availability
Data and R code supporting this manuscript are available at https://github.com/seannaman/Naman-et-al_2021_CJFAS.git.

#References
<div id="refs"></div>

#Figures

**Figure 1** Photographs of experimental cover boxes. Branches were attached to the underside of each box to simulate cover from wood (left panel). Boxes were anchored to the substrate with rebar, with the open sides of the box facing upstream perpendicular to flow. 

**Figure 2** Activity (top panel) and cover use (bottom panel) as proportions of the total number of individual bull trout and rainbow trout observed in each time period. 

**Figure 3** Boxplots showing focal velocities (top panel) and total water depth (bottom panel) occupied by foraging and resting rainbow trout in each time period. Points represent an individual fish and are jittered slightly to ease interpretation. Boxes represent the 25 and 75% quartiles and lines inside the boxes represent the medians. 

**Figure 4** Constrained Analysis of Principal Coordinates (CAP) plots for resting and foraging bull trout and rainbow trout in each time period. Arrows represent the relative contributions of different habitat factors to the constrained ordination axes, points represent the positions of individual fish observations in the ordination space, and ellipses represent the bivariate standard deviation for each of the four groups representing a combination of species and activity. Separate ordinations were performed in each time period, thus the CAP axes are on different scales for each plot. 

**Figure 5** The probability that an experimentally added cover unit will be colonized by a foraging rainbow trout as a function of the estimated net rate of energy intake (J s$^{-1}$) at the location the cover unit was placed. Points indicate individual cover boxes. The trend line and shaded region of 95% confidence are predicted from the binomial GLM. 

**Figure 6** Univariate habitat suitability curves (HSCs) for depth, velocity, substrate, and cover for rainbow trout and bull trout compared across the three time periods (day, dusk, night). HSCs are based on GLM modele predictions of observed habitat use relative to availability and are standardized to a maximum of 1. 



